//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanIt.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanItem()
        {
            this.Comments = new HashSet<Comment>();
            this.SharedPlanItemUsers = new HashSet<SharedPlanItemUser>();
        }
    
        public int Id { get; set; }
        public int PlanId { get; set; }
        public string Title { get; set; }
        public string Descripiton { get; set; }
        public Nullable<System.DateTime> Begin { get; set; }
        public Nullable<System.DateTime> End { get; set; }
        public int StatusId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> ImageId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Image Image { get; set; }
        public virtual Plan Plan { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SharedPlanItemUser> SharedPlanItemUsers { get; set; }
    }
}
